import torch
import torch.nn as nn
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import get_peft_model, LoraConfig, TaskType

class MotionQwen(nn.Module):
    def __init__(self, base_model_id, motion_dim, hidden_dim=1024, r=8, lora_alpha=32):
        super().__init__()
        
        # 1. Load Qwen Backbone & Tokenizer
        self.qwen = AutoModelForCausalLM.from_pretrained(base_model_id)
        self.tokenizer = AutoTokenizer.from_pretrained(base_model_id)
        
        # 2. Configure LoRA
        peft_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM, 
            inference_mode=False, 
            r=r, 
            lora_alpha=lora_alpha, 
            lora_dropout=0.1,
            target_modules=["q_proj", "v_proj"] 
        )
        self.qwen = get_peft_model(self.qwen, peft_config)
        
        # 3. Motion Adapter (MLP)
        self.motion_encoder = nn.Sequential(
            nn.Linear(motion_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim)
        )
        
        self.motion_decoder = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, motion_dim)
        )
        
        # 4. Special Tokens
        self.start_motion_token = nn.Parameter(torch.randn(1, 1, hidden_dim))
        # End token is trained implicitly as the target of the last frame if needed, 
        # or used during inference as a stopping condition.
        self.end_motion_token = nn.Parameter(torch.randn(1, 1, hidden_dim)) 

    def forward(self, input_ids, motion, motion_mask):
        B, T, D = motion.shape
        
        # 1. Embeddings
        transformer = self.qwen.base_model.model.model
        text_embeds = transformer.embed_tokens(input_ids) 
        motion_embeds = self.motion_encoder(motion)       
        
        start_token = self.start_motion_token.expand(B, -1, -1)
        motion_input = motion_embeds[:, :-1, :] 
        
        # Concatenate inputs
        inputs_embeds = torch.cat([text_embeds, start_token, motion_input], dim=1)
        
        # 2. CREATE ATTENTION MASK
        # Text mask comes from input_ids (1 for text, 0 for pad)
        text_mask = (input_ids != self.tokenizer.pad_token_id).long()
        
        # Start token is always 1
        start_mask = torch.ones((B, 1), device=input_ids.device)
        
        # Motion mask (1 for real frames, 0 for pad) - adjust length for input (T-1)
        motion_mask_in = motion_mask[:, :-1]
        
        # Combine
        full_attention_mask = torch.cat([text_mask, start_mask, motion_mask_in], dim=1)
        
        # 3. Pass through Qwen WITH mask
        outputs = self.qwen(
            inputs_embeds=inputs_embeds, 
            attention_mask=full_attention_mask,
            output_hidden_states=True
        )
        last_hidden_state = outputs.hidden_states[-1]
        
        # --- 4. Slice Output for Motion Prediction ---
        text_len = text_embeds.shape[1]
        
        # We only care about predictions generated by [Start ... Motion(T-2)]
        # These correspond to indices starting from `text_len` to the end.
        motion_hidden_out = last_hidden_state[:, text_len:, :]
        
        # Decode
        predicted_motion = self.motion_decoder(motion_hidden_out) # (B, Motion_Len, Motion_Dim)
        
        # --- 5. Calculate Loss ---
        # Targets are the full motion sequence M(0...T-1)
        # Start -> Predicts M0
        # M0    -> Predicts M1
        # ...
        
        loss_fn = nn.MSELoss(reduction='none')
        loss_unreduced = loss_fn(predicted_motion, motion) # (B, T, D)
        
        # Mean over feature dimension
        loss_per_frame = loss_unreduced.mean(dim=-1) # (B, T)
        
        # Apply Mask
        masked_loss = loss_per_frame * motion_mask
        
        # Normalize
        loss = masked_loss.sum() / motion_mask.sum()
        
        return loss, predicted_motion
    
    @torch.no_grad()
    def generate(self, text, max_new_tokens=120, temperature=1.0):
        """
        text: Input string
        max_new_tokens: Number of motion frames to generate
        """
        self.eval()
        device = self.qwen.device
        
        # 1. Prepare Text Inputs
        inputs = self.tokenizer(text, return_tensors="pt").to(device)
        input_ids = inputs.input_ids
        
        # 2. Get Initial Embeddings [Text + Start_Token]
        transformer = self.qwen.base_model.model.model
        text_embeds = transformer.embed_tokens(input_ids)
        
        B = text_embeds.shape[0]
        start_token = self.start_motion_token.expand(B, -1, -1)
        
        # Concatenate: [Text, Start]
        # We feed this first to prime the KV cache
        current_inputs_embeds = torch.cat([text_embeds, start_token], dim=1)
        
        past_key_values = None
        generated_frames = []
        
        # 3. Autoregressive Loop
        for _ in range(max_new_tokens):
            # Forward pass
            # output_hidden_states=True is required to get the embedding for decoding
            outputs = self.qwen(
                inputs_embeds=current_inputs_embeds,
                past_key_values=past_key_values,
                use_cache=True,
                output_hidden_states=True
            )
            
            past_key_values = outputs.past_key_values
            
            # Get the last hidden state (corresponding to the last input token)
            # Shape: (Batch, 1, Hidden_Dim)
            last_hidden_state = outputs.hidden_states[-1][:, -1:, :]
            
            # Decode to Motion Space
            pred_motion = self.motion_decoder(last_hidden_state)
            generated_frames.append(pred_motion)
            
            # Prepare input for the next step
            # The output of step T becomes the input for step T+1
            # We must encode it back to embedding space
            current_inputs_embeds = self.motion_encoder(pred_motion)
            
        # 4. Assemble Result
        # Shape: (Batch, Seq_Len, Motion_Dim)
        full_motion = torch.cat(generated_frames, dim=1)
        
        return full_motion